# Generated by Django 3.0.4 on 2021-05-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('signUpDate', models.DateTimeField()),
                ('geoState', models.CharField(max_length=30)),
                ('geoCity', models.CharField(max_length=50)),
                ('geoLocation', models.CharField(max_length=50)),
                ('mealsServed', models.CharField(max_length=30)),
                ('foodType', models.CharField(choices=[('V', 'Veg'), ('N', 'Non Veg'), ('B', 'Veg and Non Veg')], max_length=1)),
                ('cost', models.CharField(choices=[('F', 'Free'), ('P', 'Paid')], max_length=1)),
                ('serviceStatus', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('U', 'Unknown')], max_length=1)),
                ('moreDetails', models.TextField()),
            ],
        ),
    ]
