# Generated by Django 3.0.4 on 2021-05-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidmeals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealservice',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
