# Generated by Django 3.0.4 on 2021-05-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidmeals', '0002_mealservice_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealservice',
            name='cost',
            field=models.CharField(choices=[('F', 'Free'), ('P', 'Paid')], max_length=1, null=True),
        ),
    ]
